---
title: "Merging datasets"
format: html
editor: source
---

```{r}
# libraries
library(tidyverse)
library(janitor)
library(lubridate)
library(sf)
```

```{r}
# use cleaned data
ice <- read_csv('ice_encounters_cleaned.csv')

#nat_cit <- read_csv('nat_cit_cleaned.csv')
```

```{r}
# load in shapefiles
#county_shapes <- st_read("counties_shapes/USA Census Counties.shp")
#aor_shapes <- st_read("ICE_AORs_shapes/ICE AORs.shp")

aor_shapes <- st_read("merged_AOR_shapes/merged_AORs.shp")
```

```{r}
#county_shapes<- clean_names(county_shapes)
#aor_shapes<- clean_names(aor_shapes)

aor_shapes <- clean_names(aor_shapes)
```

## Some more cleaning to better fit the shapefile
```{r}
ice <- ice |>
  #rename(aor = responsible_aor) |>
  mutate(aor = gsub(" Area of Responsibility", "", aor))

head(ice)
```

```{r}
unique(ice$aor)
length(unique(ice$aor))
```
```{r}
unique(aor_shapes$aor)
length(unique(aor_shapes$aor))
```
```{r}
setdiff(ice$aor, aor_shapes$aor)
setdiff(aor_shapes$aor, ice$aor)
```

Rename AOR names to match shapefile
```{r}

aor_shapes <- aor_shapes |>
  mutate(aor = ifelse(aor == "Harlingeen", "Harlingen", aor)) |>
  select(-layer)

ice <- ice |>
  mutate(aor = ifelse(aor == "St. Paul", "St Paul", aor),
         aor = ifelse(aor == "Washington", "DC", aor))
```

```{r}
setdiff(ice$aor, aor_shapes$aor)
setdiff(aor_shapes$aor, ice$aor)
```

```{r}
ice |>
  filter(aor == "HQ") |>
  distinct(aor, responsible_site)
```

```{r}
ice <- ice |>
  mutate(aor = ifelse(aor == "HQ" & responsible_site == "ERO - Pacific Enforcement Response Center", "Los Angeles", aor),
         aor = ifelse(aor == "HQ" & responsible_site == "WASHINGTON, DC, (HQ) DOCKET CONTROL OFFICE", "DC", aor))
```

```{r}
write.csv(ice, "/Users/gabriellelow/Downloads/ICE mapping project/ice_encounters_cleaned.csv", row.names = FALSE)
```





```{r}
aor_clean <- aor_shapes |>
  mutate(geometry = st_make_valid(geometry))  # fixes invalid geometries
```

```{r}
st_write(aor_clean, "/Users/gabriellelow/Downloads/ICE mapping project/aors_counties.shp", driver="ESRI Shapefile")
```


```{r}
aor_dissolved <- aor_clean |>
  group_by(aor) |>
  summarize(geometry = st_union(geometry)) 

merged <- left_join(aor_dissolved, ice, by = "aor")
```

```{r}
nrow(merged)
```

```{r}
write.csv(merged, "/Users/gabriellelow/Downloads/ICE mapping project/encounters_aors_merged.csv", row.names = FALSE)
```

```{r}
st_write(merged, "/Users/gabriellelow/Downloads/ICE mapping project/encounters_aors_merged.shp", driver="ESRI Shapefile")
```

```{r}
encounters_aors_merged <- st_read('encounters_aors_merged.shp')
```

```{r}
aors_dissolved <- st_read("aor_shapefile_dissolved.shp")
```
```{r}
merged <- left_join(ice, aors_dissolved, by = "aor")
```

